services:
  - type: web
    name: shorttermemail-api
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: REDIS_URL
        fromDatabase:
          name: redis
          property: connectionString

databases:
  - name: redis
    plan: free
    type: redis